apiVersion: v1
kind: Secret
metadata:
  name: aria-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "aria_secret"
  GROQ_API_KEY: "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"
  TAVILY_API_KEY: "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"
  OPENWEATHERMAP_API_KEY: "879028dddbd207f012ef74e9b25d83fb"